"""Output validation and grounding checks."""

import re
from typing import Dict, Any, Tuple, List

# Pitch-specific constants
MAX_PITCH_LENGTH = 5000  # ~4 paragraphs max
_EMAIL_PATTERN = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")
_PHONE_PATTERN = re.compile(r"(?:\+?\d{1,3}[\s-]?)?\(?\d{2,4}\)?[\s.-]?\d{3,4}[\s.-]?\d{3,4}")
_FABRICATED_URL_PATTERN = re.compile(
    r"https?://(?!www\.)[a-z]+\.(?:com|org|net)/[a-z0-9/_-]{20,}", re.I
)
_UNPROFESSIONAL_PATTERNS = [
    re.compile(r"\b(fuck|shit|damn|bastard|ass(?:hole)?|crap|dick|bitch)\b", re.I),
    re.compile(r"\b(lol|lmao|rofl|wtf|omg|bruh)\b", re.I),
    re.compile(r"\b(😂|🤣|💩|🖕)", re.I),
]


def validate_resume_output(result: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Validate resume parser output has required structure."""
    issues = []
    info = result.get("resume_info", {})
    if not info:
        issues.append("resume_info is empty")
    if not isinstance(info, dict):
        issues.append("resume_info is not a dict")
    return (len(issues) == 0, issues)


def validate_job_discovery_output(result: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Validate job discovery output."""
    issues = []
    scored = result.get("scored_jobs", [])
    if not isinstance(scored, list):
        issues.append("scored_jobs is not a list")
    for i, job in enumerate(scored[:5]):
        if not isinstance(job, dict):
            issues.append(f"scored_jobs[{i}] is not a dict")
            continue
        if "score" not in job:
            issues.append(f"scored_jobs[{i}] missing 'score'")
        if "title" not in job:
            issues.append(f"scored_jobs[{i}] missing 'title'")
    return (len(issues) == 0, issues)


def validate_pitch_output(result: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Validate pitch generator output."""
    issues = []
    pitch = result.get("final_pitch", "")
    if not pitch:
        issues.append("final_pitch is empty")
    if isinstance(pitch, str) and len(pitch) < 50:
        issues.append("final_pitch is suspiciously short")
    if isinstance(pitch, str) and len(pitch) > MAX_PITCH_LENGTH:
        issues.append(f"final_pitch exceeds max length ({MAX_PITCH_LENGTH} chars)")
    return (len(issues) == 0, issues)


def check_pitch_pii_leakage(pitch: str) -> Tuple[bool, List[str]]:
    """Check that the generated pitch does not leak PII like email or phone.

    Cover letters should not contain raw contact details — those belong in
    a separate header, not in the body generated by the LLM.
    """
    issues = []
    if _EMAIL_PATTERN.search(pitch):
        issues.append("pitch contains an email address — possible PII leakage")
    if _PHONE_PATTERN.search(pitch):
        issues.append("pitch contains a phone number — possible PII leakage")
    return (len(issues) == 0, issues)


def check_pitch_professionalism(pitch: str) -> Tuple[bool, List[str]]:
    """Flag unprofessional or offensive language in the generated pitch."""
    issues = []
    for pattern in _UNPROFESSIONAL_PATTERNS:
        match = pattern.search(pitch)
        if match:
            issues.append(f"pitch contains unprofessional language: '{match.group()}'")
    return (len(issues) == 0, issues)


def check_pitch_grounding(
    pitch: str, candidate_skills: list, candidate_name: str | None = None
) -> Tuple[float, List[str]]:
    """Verify the pitch references actual candidate skills, not fabricated ones.

    Returns (grounding_score 0.0–1.0, list of warnings).
    A score below 0.3 suggests the pitch may be hallucinating qualifications.
    """
    warnings: list[str] = []
    if not candidate_skills:
        return (1.0, [])  # Nothing to check against

    pitch_lower = pitch.lower()
    matched = 0
    for skill in candidate_skills:
        if skill.lower() in pitch_lower:
            matched += 1

    score = matched / len(candidate_skills) if candidate_skills else 1.0

    if score < 0.3:
        warnings.append(
            f"pitch references very few candidate skills ({matched}/{len(candidate_skills)}) "
            "— may contain fabricated qualifications"
        )

    return (score, warnings)


def check_pitch_fabrication(pitch: str) -> Tuple[bool, List[str]]:
    """Detect common hallucination markers in the generated pitch.

    Checks for fabricated URLs, invented percentages/metrics that the LLM
    may have hallucinated, and placeholder text left by the model.
    """
    issues = []

    # Check for suspicious fabricated URLs (long random-looking paths)
    fabricated_urls = _FABRICATED_URL_PATTERN.findall(pitch)
    if fabricated_urls:
        issues.append(f"pitch contains possibly fabricated URL(s): {fabricated_urls[:2]}")

    # Check for placeholder text the LLM may leave in
    placeholder_patterns = [
        r"\[your name\]",
        r"\[company name\]",
        r"\[insert ",
        r"\[fill in",
        r"\[add ",
        r"\[recipient",
        r"\[hiring manager\]",
        r"\[date\]",
    ]
    for pat in placeholder_patterns:
        if re.search(pat, pitch, re.I):
            issues.append(f"pitch contains placeholder text matching '{pat}'")

    return (len(issues) == 0, issues)


def validate_market_intel_output(result: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """Validate market intelligence output has required structure and data quality."""
    issues = []

    # skill_gaps validation
    skill_gaps = result.get("skill_gaps", [])
    if not isinstance(skill_gaps, list):
        issues.append("skill_gaps is not a list")
    else:
        for i, gap in enumerate(skill_gaps[:10]):
            if not isinstance(gap, dict):
                issues.append(f"skill_gaps[{i}] is not a dict")
                continue
            if not gap.get("skill"):
                issues.append(f"skill_gaps[{i}] missing 'skill'")
            if gap.get("importance") and gap["importance"] not in ("high", "medium", "low"):
                issues.append(f"skill_gaps[{i}] invalid importance: {gap['importance']}")
            if gap.get("category") and gap["category"] not in ("technical", "soft", "certification"):
                issues.append(f"skill_gaps[{i}] invalid category: {gap['category']}")

    # upskilling_roadmap validation
    roadmap = result.get("upskilling_roadmap", [])
    if not isinstance(roadmap, list):
        issues.append("upskilling_roadmap is not a list")
    else:
        for i, item in enumerate(roadmap[:10]):
            if not isinstance(item, dict):
                issues.append(f"upskilling_roadmap[{i}] is not a dict")
                continue
            if not item.get("skill"):
                issues.append(f"upskilling_roadmap[{i}] missing 'skill'")
            if "priority" in item and not isinstance(item["priority"], (int, float)):
                issues.append(f"upskilling_roadmap[{i}] priority is not a number")

    # salary_insights validation
    salary = result.get("salary_insights", {})
    if salary and not isinstance(salary, dict):
        issues.append("salary_insights is not a dict")
    elif isinstance(salary, dict) and salary:
        for field in ("min_salary", "max_salary", "median_salary"):
            val = salary.get(field)
            if val is not None and not isinstance(val, (int, float)):
                issues.append(f"salary_insights.{field} is not a number")
        if salary.get("min_salary") and salary.get("max_salary"):
            if salary["min_salary"] > salary["max_salary"]:
                issues.append("salary_insights.min_salary > max_salary")

    # industry_trends validation
    trends = result.get("industry_trends", [])
    if not isinstance(trends, list):
        issues.append("industry_trends is not a list")

    # market_outlook validation
    outlook = result.get("market_outlook", "")
    if outlook and not isinstance(outlook, str):
        issues.append("market_outlook is not a string")

    return (len(issues) == 0, issues)


def check_grounding(summary: str, state: Dict[str, Any]) -> float:
    """Simple grounding check — verify summary references state data.

    Returns a grounding score 0.0–1.0 based on how many state fields are referenced.
    """
    if not summary:
        return 0.0

    summary_lower = summary.lower()
    checks = 0
    found = 0

    # Check if resume info is referenced
    info = state.get("resume_info", {})
    contact = info.get("contact_info", {}) if isinstance(info, dict) else {}
    name = contact.get("name") if isinstance(contact, dict) else None
    if name:
        checks += 1
        if name.lower() in summary_lower:
            found += 1

    # Check if top job is referenced
    scored = state.get("scored_jobs", [])
    if scored and isinstance(scored[0], dict):
        top_company = scored[0].get("company", "")
        if top_company:
            checks += 1
            if top_company.lower() in summary_lower:
                found += 1

    # Check if skill gaps are referenced
    gaps = state.get("skill_gaps", [])
    if gaps:
        checks += 1
        if any(
            g.get("skill", "").lower() in summary_lower
            for g in gaps[:3] if isinstance(g, dict)
        ):
            found += 1

    if checks == 0:
        return 1.0  # Nothing to check
    return found / checks
